### ISSUE TITLE
Issue when using multiple "or" or "and"

### ISSUE THREAD

**Issue by mohankumaru** [15five/scim2-filter-parser#17] opened 2020-10-15 09:16 UTC
Hi,

I am facing an issue, where the query having two or more "and" or more than two "or" is failing.
Have a look at examples below: - 

1)```"displayName co \"username\" or nickName co \"username\" or userName co \"username\""```
   ```"displayName co \"username\" and nickName co \"username\" and userName co \"username\""```

the two queries fails giving ,
```scim2_filter_parser.parser.SCIMParserError: Parsing error at: Token(type='OR', value='or', lineno=1, index=52)```
 
notice above queries are having either only "or" or "and".

2)```"displayName co \"username\" and nickName co \"username\" or userName co \"username\""```
but this query works.

**Comment by logston** [comment] 2020-10-15 13:36
Thanks for the report! It might be a few weeks before I am able to fix this, FYI.

**Comment by mohankumaru** [comment] 2020-10-15 14:22
Did you test it for those examples? Just to be sure, if I am doing anything wrong.

**Comment by logston** [comment] 2020-10-16 23:36
Based on the RFC on which I designed this library, https://tools.ietf.org/html/rfc7644#section-3.4.2.2, it looks like you queries are compliant. 

Here they are side by side:

```
displayName co "username"  or nickName co "username"  or userName co "username"  # does not work 
displayName co "username" and nickName co "username" and userName co "username"  # does not work 
displayName co "username" and nickName co "username"  or userName co "username"  # works
```

**Comment by logston** [comment] 2020-10-16 23:38
The only difference I can find is one of order in the "and"s and "or"s. I'll write a few unit tests to see if I can reproduce the issue.

**Comment by logston** [comment] 2020-10-18 03:30
I've reproduced the issue and it is with the parser. The lexer is working fine. I'll see about resolving this issue in the next week or so.

**Comment by logston** [comment] 2020-10-24 21:25
Pardon the delay on this. Given the complexity of this issue, there might not be a resolution for the issue for several weeks months. We only work on issues on this repo on Fridays. In the meantime, feel free to pull the branch in the PR that adds the unit tests and begin to work on a solution. If you do, please make a note here so that effort is not duplicated.

**Comment by mohankumaru** [comment] 2020-10-27 05:04
Could there be any temporary solution for this case? Probably an hardcoded solution.

**Closed** 2020-10-31 04:31 UTC

**Comment by logston** [comment] 2020-10-31 04:35
This should be fixed?

**Comment by mohankumaru** [comment] 2020-10-31 06:10
Yes, now its working as expected. Thank you.
